version: '3'

services:
  php-apache:
    build:
      context: ./php-apache
    ports:
      - 80:80
    volumes:
      - ./php-apache/src:/var/www/html
    links:
      - mariadb

  mariadb:
    image: mariadb:latest
    volumes:
      - ./mariadb:/var/lib/mysq1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
